services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - VITE_API=${VITE_API}
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/frontend/dist
      - /etc/letsencrypt:/etc/letsencrypt
      - https_challenge:/var/lib/letsencrypt
    depends_on:
      - backend
      - frontend
volumes:
  https_keys: {}
  https_challenge: {}
